### ISSUE TITLE
High CPU usage and severe memory leak after upgrading to ElmahCore 2

### ISSUE THREAD

**Issue by agrinei** [ElmahCore/ElmahCore#88] opened 2021-02-18 14:54 UTC
I've been using Elmah v 1.2 for a long time with no issues. Last weekend I moved my aspnet core website to .Net 5.0 and ElmahCore 2.0.6. Right after that I noticed a very high CPU usage and a memory leak that would eat all memory in a couple of minutes. 

Analyzing a memory dump I've found suspect entries:

00007ff922cd08c8    80722      2583104 System.Collections.Generic.List`1[[ElmahCore.ErrorLogEntry, ElmahCore]]
00007ff9207510f0   161498      5167936 System.Decimal
00007ff92143b7a0    80838      5820336 System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib]]
00007ff9207cd778    16571      7660652 System.Byte[]
00007ff922cd0838   261169     10446760 ElmahCore.ErrorLogEntry
00007ff922cd1410   161445     11166704 ElmahCore.ErrorLogEntry[]
00007ff920752990    15266     12954908 System.Int32[]
00007ff920757a90   387225     19358942 System.String
00007ff920881058   524027     37729944 System.Collections.Hashtable
00007ff9212e73b0   522339     41787120 System.Collections.Specialized.NameValueCollection
00007ff92187b230   261170     41787200 ElmahCore.Error
00007ff920775998  2183474     70004992 System.String[]
00007ff9242b8868  7051567    225650144 System.Collections.Specialized.NameObjectCollectionBase+NameObjectEntry
00007ff921305470  7573908    242365056 System.Collections.ArrayList
00007ff9208813f0   766184    321624144 System.Collections.Hashtable+bucket[]
00007ff920696860  7872966    346213040 System.Object[]

My guess is that an error inside Elmah 2 is being handled by the Elmah 2 routines, generating the same error again and again. Unfortunately I couldn't come up with a simple way to reproduce it because I had to immediately rollback the upgrade.

After downgradind to Elmah 1.2 everything went back to normal.

**Comment by User00015** [comment] 2021-06-10 14:46
Running into the same issue here. Just upgraded ElmahCore to 2.0.6 on VS2019 running .Net5. Saw the IIS Express Worker Process spike to over 10Gb (!!) before I killed it. I wasn't seeing this issue before upgrading.

**Comment by Kashif-datamagnetics** [comment] 2021-06-25 13:01
Any update here? We are facing same issue.

**Comment by mtariqdmt** [comment] 2021-06-25 13:02
Facing same issue, Any update please

**Comment by hamidkhandatamagnetics** [comment] 2021-06-25 13:03
Is there any near future fix is coming or we have to roll back to previous version ?

**Comment by ghazanfardmt** [comment] 2021-06-25 13:03
Yeah.. facing same problem. Need an urgent fix.

**Comment by raosafdar** [comment] 2021-06-25 13:03
Any Update Plz We need Solution desperately

**Comment by waqas780** [comment] 2021-06-25 13:03
consuming too much memory, system stuck due to this issue ,please solve ASAP

**Comment by kashifsohail** [comment] 2021-06-25 13:04
we are also facing same issue. need solution ASAP

**Comment by SohailLatif** [comment] 2021-06-25 13:05
any update on this issue ??

**Comment by Kashif-datamagnetics** [comment] 2021-08-02 13:17
Any update here please?

**Comment by jempc** [comment] 2021-08-04 08:17
Is there an update on this?

**Comment by SohailLatif** [comment] 2021-08-06 13:11
any update ?

**Comment by sgldev** [comment] 2021-08-10 10:34
Can you give us an ETA for when this will be fixed?

**Comment by davidglassborow** [comment] 2021-08-28 11:54
I'm also having the same issue.  We are also using SignalR in the same process, is anyone else also doing this in case it's related ?

**Comment by cheese83** [comment] 2021-08-31 14:08
We (I work with @davidglassborow) have determined that, in our case at least, the cause was an infinite loop in `GetNewErrorsAsync`. Although we had previously worked around this issue by not making any calls to `/elmah/api/new-errors` ourselves, we hadn't noticed that ElmahCore's web interface makes requests to that endpoint.

The issue was reported and fixed some time ago in #108. We just need a new version to be released to NuGet.

Until then, a workaround is to not make any calls to `/elmah/api/new-errors` (`/elmah/api/errors` can be used instead), and not use the web interface.

**Comment by Kashif-datamagnetics** [comment] 2021-08-31 16:39
@cheese83 @davidglassborow when this will be release to Nuget? I can see last version updated (2.0.6) was done 7 month ago. **Any updated is highly appreciated**

**Comment by davidglassborow** [comment] 2021-08-31 17:07
> @cheese83 @davidglassborow when this will be release to Nuget? I can see last version updated (2.0.6) was done 7 month ago. **Any updated is highly appreciated**

No idea, we are not maintainers, just users

**Closed** 2021-08-31 17:59 UTC

**Comment by ElmahCore** [comment] 2021-08-31 18:02
Thanks to @cheese83 & @davidglassborow  for localizing the error.

**Comment by davidglassborow** [comment] 2021-08-31 18:04
Thanks for the new release @ElmahCore, we appreciate it 👍
